[tool.poetry]
name = "hello-world"
version = "0.1.0"
description = ""
authors = ["Tipuch"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1"
uvicorn = "^0.11.8"
psycopg2-binary = "^2.8.5"

[tool.poetry.dev-dependencies]
yapf = "^0.30.0"
