# Generated by Django 3.0.5 on 2020-04-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender',
                 models.IntegerField(choices=[('male',
                                               0), ('female',
                                                    1), ('undisclosed', 2)])),
            ],
        ),
    ]
